-- Havitive schema (ported from the Laravel/MySQL database; table and column names kept as-is)

create table public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.admins where user_id = (select auth.uid()));
$$;

create table public.homes (
  id bigint generated by default as identity primary key,
  category text check (category in ('about','service','residence','latest','choose')),
  main_content text, meta_title text, meta_descp text, home_images text,
  description text, description_head text, icon text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.home_banners (
  id bigint generated by default as identity primary key,
  home_images text, heading text, description text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.counters (
  id bigint generated by default as identity primary key,
  counter_name text, counter text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.sectors (
  id bigint generated by default as identity primary key,
  sector_name text, category integer,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.project_aminities (
  id bigint generated by default as identity primary key,
  aminity_name text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.latest_projects (
  id bigint generated by default as identity primary key,
  meta_title text, meta_descp text, project_name text, project_image text,
  sector_id integer, aminities_id text, location text, main_content text,
  main_description text, project_image_one text, project_heading text, description text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.floors (
  id bigint generated by default as identity primary key,
  project_id integer, floor_name text, description text, image text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.project_facitities (
  id bigint generated by default as identity primary key,
  project_id integer, facility_name text, facility_description text, facility_image text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.galleries (
  id bigint generated by default as identity primary key,
  project_id integer, gallery text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.residenceprojects (
  id bigint generated by default as identity primary key,
  meta_title text, meta_descp text, main_content text, sector_id integer, main_description text,
  residence_image_one text, residence_image_two text, project_heading text, project_descp text,
  project_category text, client_name text, project_date text, location text, project_dec_two text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.upcomming_projects (
  id bigint generated by default as identity primary key,
  main_content text, main_description text, sector_id integer,
  residence_image_one text, residence_image_two text, project_heading text, project_descp text,
  project_category text, client_name text, project_date text, location text, project_dec_two text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.gropuof_companies (
  id bigint generated by default as identity primary key,
  company_name text, company_description text, compani_img text, compani_logo text, link text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.teams (
  id bigint generated by default as identity primary key,
  name text, category text check (category in ('management','team')), linkedin text, designation text,
  img text, experience text, location text, practice_area text, project_done text,
  phone text, email text, about text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.sections (
  id bigint generated by default as identity primary key,
  section_name text, img text, icon text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.services (
  id bigint generated by default as identity primary key,
  name text, section_id text, description text, img text, section text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.testimonials (
  id bigint generated by default as identity primary key,
  img text, desription text, client_img text, client_name text, client_designation text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.clients (
  id bigint generated by default as identity primary key,
  img text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.blog_categories (
  id bigint generated by default as identity primary key,
  category_name text not null, category_slug text not null,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.blog_posts (
  id bigint generated by default as identity primary key,
  blogcat_id integer not null, meta_title text, meta_descp text, post_title text, post_slug text,
  post_image text, short_descp text, long_descp text, post_tags text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.alljobs (
  id bigint generated by default as identity primary key,
  title text not null, description text not null,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

-- Visitor submissions
create table public.applies (
  id bigint generated by default as identity primary key,
  name text, email text, phone text, service_type text, message text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table public.career_pages (
  id bigint generated by default as identity primary key,
  job_id integer, name text not null, email text not null, phone text not null,
  cover_letter_path text not null, cv_path text not null, message text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

-- Row level security
alter table public.admins enable row level security;
create policy "admins read self" on public.admins for select to authenticated
  using (user_id = (select auth.uid()));

do $$
declare t text;
begin
  foreach t in array array['homes','home_banners','counters','sectors','project_aminities','latest_projects',
    'floors','project_facitities','galleries','residenceprojects','upcomming_projects','gropuof_companies',
    'teams','sections','services','testimonials','clients','blog_categories','blog_posts','alljobs']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy "public read" on public.%I for select to anon, authenticated using (true)', t);
    execute format('create policy "admin insert" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);
    execute format('create policy "admin update" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);
    execute format('create policy "admin delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
  foreach t in array array['applies','career_pages']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy "anyone submits" on public.%I for insert to anon, authenticated with check (true)', t);
    execute format('create policy "admin read" on public.%I for select to authenticated using ((select public.is_admin()))', t);
    execute format('create policy "admin delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

-- Storage: public site images, private job applications
insert into storage.buckets (id, name, public) values ('upload', 'upload', true)
  on conflict (id) do nothing;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('applications', 'applications', false, 2097152,
    array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
  on conflict (id) do nothing;

create policy "admin write upload" on storage.objects for insert to authenticated
  with check (bucket_id = 'upload' and (select public.is_admin()));
create policy "admin update upload" on storage.objects for update to authenticated
  using (bucket_id = 'upload' and (select public.is_admin()));
create policy "admin delete upload" on storage.objects for delete to authenticated
  using (bucket_id = 'upload' and (select public.is_admin()));
create policy "anyone uploads application" on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'applications');
create policy "admin reads applications" on storage.objects for select to authenticated
  using (bucket_id = 'applications' and (select public.is_admin()));
create policy "admin deletes applications" on storage.objects for delete to authenticated
  using (bucket_id = 'applications' and (select public.is_admin()));
