-- Careers redesign: richer job openings, an application pipeline with replies, and editable careers page content.

-- Job openings ---------------------------------------------------------------
alter table public.alljobs
  add column if not exists code text,
  add column if not exists department text,
  add column if not exists location text default 'Kochi, Kerala',
  add column if not exists employment_type text default 'Full-time',
  add column if not exists experience text,
  add column if not exists summary text,
  add column if not exists status text not null default 'open',
  add column if not exists sort_order integer not null default 0;

-- Applications ---------------------------------------------------------------
alter table public.career_pages
  add column if not exists location text,
  add column if not exists linkedin text,
  add column if not exists cover_letter text,
  add column if not exists status text not null default 'new',
  add column if not exists notes text,
  add column if not exists read_at timestamptz;
alter table public.career_pages alter column cover_letter_path drop not null;
create index if not exists career_pages_status_idx on public.career_pages (status, created_at desc);

-- Visitors may only fill in the application itself, never the status or notes.
revoke insert on public.career_pages from anon, authenticated;
grant insert (job_id, name, email, phone, location, linkedin, cover_letter, message, cv_path, cover_letter_path)
  on public.career_pages to anon, authenticated;
grant update, delete, select on public.career_pages to authenticated;

-- Admin replies to applicants (history of every email sent).
create table if not exists public.application_replies (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.career_pages (id) on delete cascade,
  subject text not null,
  body text not null,
  sent boolean not null default false,
  error text,
  sent_by text,
  created_at timestamptz not null default now()
);
create index if not exists application_replies_app_idx on public.application_replies (application_id, created_at);
alter table public.application_replies enable row level security;
create policy "admin all" on public.application_replies for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

-- Careers page content (one row) --------------------------------------------
create table if not exists public.careers_page (
  id bigint generated by default as identity primary key,
  hero_kicker text,
  hero_title text,
  hero_text text,
  hero_image text,
  hero_image_alt text,
  openings_kicker text,
  openings_title text,
  openings_text text,
  life_title text,
  life_text text,
  life_points text,
  life_image text,
  life_image_alt text,
  talent_title text,
  talent_text text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.careers_page enable row level security;
create policy "public read" on public.careers_page for select using (true);
create policy "admin insert" on public.careers_page for insert to authenticated with check ((select public.is_admin()));
create policy "admin update" on public.careers_page for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "admin delete" on public.careers_page for delete to authenticated using ((select public.is_admin()));

insert into public.careers_page (hero_kicker, hero_title, hero_text, openings_kicker, openings_title, openings_text,
  life_title, life_text, life_points, talent_title, talent_text)
select
  'Careers at Havitive',
  'Build the spaces people live, work and grow in',
  'Join a team of architects, engineers and project managers delivering landmark residential, commercial and government projects across Kerala. We value craft, ownership and continuous learning.',
  'Current Openings',
  'Explore Opportunities',
  'Find a role that matches your skills and ambitions. Open any position to read the full job description and apply in a minute.',
  'Life at Havitive',
  'We are a close-knit, design-led team. You will work on real projects from the first week, learn from senior professionals and see your ideas built.',
  E'Hands-on work on live projects\nMentoring from senior architects and engineers\nSite exposure across Kerala\nGrowth path with regular reviews\nCollaborative, respectful workplace',
  'Join our talent network',
  'Don''t see the right role? Drop your CV and we will contact you when a suitable position opens.'
where not exists (select 1 from public.careers_page);

-- CVs up to 5 MB.
update storage.buckets set file_size_limit = 5242880 where id = 'applications';
